############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

proxy: https://goproxy.cn

imports:
  - path: github.com/wangguansong/wowchemy/modules/wowchemy-one
